# Generated by Django 4.0.5 on 2022-06-23 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_review_movie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='user',
            new_name='critic',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='movie',
            new_name='movie_id',
        ),
    ]
